#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  13 November 2017                   #
#-------------------------------------------------#
# Topic:       ACMI Tutorial and snappyHexMesh    #
# OpenFOAM:    5.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-5.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Extract feature edges"
surfaceFeatureExtract >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (~ 120 seconds)"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Extrude one patch to make a 2D mesh"
flattenMesh >> logMeshing
extrudeMesh >> logMeshing
rm -rf 0 constant/polyMesh/*Level


#------------------------------------------------------------------------------
echo -e "   - Merge baffle + interface, and remove not necessary boundaries" 
cp system/createPatchDict.first system/createPatchDict
createPatch -overwrite  >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Using interface patches to create faceSets and using the"
echo -e "     the faceSets to create faceZones (correct orientation and faces)"
echo -e "     In addition we create the moving cellZone (for motion)"
topoSet >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Create ACMI interfaces using the faceZones"
rm -rf 0
createBaffles -overwrite >> logMeshing 2>&1

#------------------------------------------------------------------------------
echo -e "   - Remove zero-face entries in boundary file"
cp system/createPatchDict.second system/createPatchDict
createPatch -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Renumber the mesh for speedup"
renumberMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.orig to 0"
cp -r 0.orig 0


#------------------------------------------------------------------------------
if [ `which laplacianDyMFoam` ]
then
    echo -e "   - Start simulation (approximately 5-10min)"
    laplacianDyMFoam > logSimulation
else
    echo -e "   - Can not start simulation, 'laplacianDyMFoam' not available"
    echo -e "   - Available on https://bitbucket.org/shor-ty/laplaciandymfoam"
fi


#------------------------------------------------------------------------------
echo -e "\nEnd\n\n"


#------------------------------------------------------------------------------
